# Generated by Django 6.0.3 on 2026-03-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='support_attachments/'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='admin_unread_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user_unread_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
