# Generated by Django 6.0.3 on 2026-03-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_supportmessage_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='is_breaking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newspost',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
