# Generated by Django 6.0.3 on 2026-03-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_newspost_is_breaking_newspost_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='editor_name',
            field=models.CharField(default='Daily Buzz Editorial Desk', max_length=120),
        ),
    ]
