# Generated by Django 6.0.3 on 2026-03-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_newspost_editor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Daily Buzz Updates', max_length=120)),
                ('site_tagline', models.CharField(default='Fast, smart, and reliable updates', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site_branding/')),
                ('homepage_banner_title', models.CharField(default='Welcome to Daily Buzz Updates', max_length=200)),
                ('homepage_banner_subtitle', models.TextField(default='Stay informed with breaking news, featured reports, and premium stories.')),
                ('support_email', models.EmailField(default='dupdateske@gmail.com', max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='newspost',
            name='show_in_carousel',
            field=models.BooleanField(default=False),
        ),
    ]
