# Generated by Django 6.0.3 on 2026-03-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_sitesetting_newspost_show_in_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='show_as_popup',
            field=models.BooleanField(default=False),
        ),
    ]
