# Generated by Django 6.0.3 on 2026-03-12 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('news', 'News Article'), ('video', 'Video')], max_length=10)),
                ('category', models.CharField(choices=[('entertainment', 'Entertainment'), ('sports', 'Sports'), ('politics', 'Politics'), ('technology', 'Technology'), ('business', 'Business'), ('health', 'Health')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='submission_images/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='submission_videos/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
