# Generated by Django 6.0.3 on 2026-03-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup'), ('password_change', 'Password Change'), ('phone_change', 'Phone Change')], default='signup', max_length=30),
        ),
    ]
