# Generated by Django 6.0.3 on 2026-03-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_address_emailverificationcode_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup'), ('password_change', 'Password Change'), ('phone_change', 'Phone Change'), ('delete_account', 'Delete Account')], default='signup', max_length=30),
        ),
    ]
