# Generated by Django 6.0.3 on 2026-03-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_is_premium_customuser_premium_since_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='premium_revoke_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='premium_revoked',
            field=models.BooleanField(default=False),
        ),
    ]
